### ISSUE TITLE
Bug Alert!

### ISSUE THREAD

**Issue by janja-janja** [uonbi/quiz_engine#1]
@shimanyi  Fix the reg_user(x, y) function in the quiz controller. It should take 3 params, i.e phone, msg, time. Fix to avoid conflicts. 
![screenshot from 2015-03-05 00 18 14](https://cloud.githubusercontent.com/assets/9822841/6493653/2b57b150-c2cd-11e4-82b2-642347982765.png)

**Comment by shimanyi** [comment]
Done :)
