### ISSUE TITLE
Install Curl module

### ISSUE THREAD

**Issue by janja-janja** [uonbi/quiz_engine#2]
@shimanyi  The AfricasTalkingGateway requires we have curl in our servers. Intergrate that as well for the server.

**Comment by janja-janja** [comment]
@shimanyi    sudo apt-get install php5-curl     --> locallly

**Comment by shimanyi** [comment]
@denisKaranja  Bro, I have setup some thunt.shimanyi.me application that we can use. The configurations for the curl seems to take sometime but I am on top of it. It should not take me too long to have it up

**Comment by shimanyi** [comment]
After struggling a little I found this http://blog.webfaction.com/2012/02/a-look-at-our-php-setup/ so the webfaction guys have set it up already .... let us just dive in and use it :+1:
