### ISSUE TITLE
Could we remove the .py files for now ?

### ISSUE THREAD

**Issue by shimanyi** [uonbi/quiz_engine#4]
I just have ADD with this bro, could we remove the python files here? If they didn't serve any purpose in the php code, we can do without them I guess.

**Comment by janja-janja** [comment]
Sure, fixing that in a moment.                                                                                                                                                                                                                                                                          Sent from my not so very smart phone.                                                                                                                                                                                                                                         From: shimanyi valentinoSent: Thursday, March 5, 2015 09:21To: uonbi/quiz_engineReply To: uonbi/quiz_engineSubject: [quiz_engine] Could we remove the .py files for now ? (#4)I just have ADD with this bro, could we remove the python files here? If they didn't serve any purpose in the php code, we can do without them I guess. 

—Reply to this email directly or view it on GitHub.

**Comment by obanda** [comment]
english mamguys...acheni u-nandaa ... ni OCD si ADD

On Thu, Mar 5, 2015 at 9:21 AM, shimanyi valentino <notifications@github.com

> wrote:
> 
> I just have ADD with this bro, could we remove the python files here? If
> they didn't serve any purpose in the php code, we can do without them I
> guess.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uonbi/quiz_engine/issues/4.

## 

_letishar_
