### ISSUE TITLE
Bug report!

### ISSUE THREAD

**Issue by janja-janja** [uonbi/quiz_engine#5]
@shimanyi  Semicolon missing on helper function probation_reset()
![screenshot from 2015-03-05 11 25 36](https://cloud.githubusercontent.com/assets/9822841/6501524/7198b15c-c32a-11e4-95f7-4d087816885f.png)

**Comment by shimanyi** [comment]
in the data['probation_status'] ? It is okay that way cause it the only item in the array ... has it given a compiler error ? I doubt it should :100:

**Comment by janja-janja** [comment]
@shimanyi Parse error: syntax error, unexpected '=', expecting ')' in /var/www/CI_apps/quiz_engine/app/application/models/quiz_model.php on line 155

**Comment by shimanyi** [comment]
aaaa.... it it this ' > '  thanks :+1:

**Comment by janja-janja** [comment]
@shimanyi Cool!! Push it so i can merge
